from manim import *

####################################################################
# "titre" means "title" in french                                  #
# All text/math lines variable's starts with "eq"                  #
# All braces starts with "b"                                       #
# The variables in the first part have an l in them for "lemma"    #
# I hope it's clear, if not you can send me a message              #
####################################################################

class sqrt2irra(Scene):
    def construct(self):
        titre1 = MathTex("\\text{Let's prove that } \\sqrt{2} \\text{ is irrational}")
        titre = MathTex("\\underline{\\text{Proving that } \\sqrt{2} \\text{ is irrational}}").to_edge(UP)
        
        #Part1
        soustitrel1 = MathTex("\\text{First we need to prove than an odd number squared is odd}").scale_in_place(0.75)
        soustitrel2 = MathTex("\\text{Preparation : proving that an odd number squared is odd}").scale_in_place(0.75)
        eql0a = MathTex("\\text{Let } n \\in \\mathbb{Z} \\text{, an odd number.")
        eql0b = MathTex("\\text{We have : }","n = 2k + 1" ,"\\text{, with } k \in \mathbb{Z}")
        eql1 = MathTex("n = 2k + 1")
        bl1 = BraceLabel(eql1,"\\text{We square each side }",brace_direction=UP)
        eql2 = MathTex("n^2 =", "(2k + 1)^2")
        bl2 = BraceLabel(eql2[1],"\\text{We can expand using } (a+b)^2 = a^2 + 2ab + b^2")
        eql3 = MathTex("n^2 = ","4k^2 + 4k"," + 1")
        bl3 = BraceLabel(eql3[1],"\\text{We can factor by } 2")
        eql4 = MathTex("n^2 = 2","(2k^2 + 2k)","+ 1")
        bl4 = BraceLabel(eql4[1],"\\text{Now let } q = (2k^2 + k)")
        eql5 = MathTex("n^2 =","2q","+ 1")
        bl5a = BraceLabel(eql5[1],"\\text{This is even }",brace_direction=UP)
        bl5b = BraceLabel(eql5[1:],"\\text{So this is odd }")
        eql6 = MathTex("\\text{Conclusion : }","(n \\text{ odd}) \\implies (n^2 \\text{ odd})")
        bl6 = BraceLabel(eql6[1],"\\text{\\emph{Note}: This is equivalent to } (n^2 \\text{ even}) \\implies (n \\text{ even})")
        
        
        #Part2
        soustitre1 = MathTex("\\text{Now it's time for the actual proof.}")
        soustitre2a = MathTex("\\text{To show that } \\sqrt{2} \\text{ is irrational}").scale_in_place(0.75)
        soustitre2b = MathTex("\\text{we will suppose that it is rational and find a contradiction.}").next_to(soustitre2a,DOWN).scale_in_place(0.75)
        soustitre3a = MathTex("\\text{If } \\sqrt{2} \\in \\mathbb{Q} \\text{, we can write } \\sqrt{2} = \\frac{a}{b}").scale_in_place(0.75)
        soustitre3b = MathTex(" \\text{ with } a \\in \\mathbb{Z} \\text{ and } b \\in \\mathbb{Z}^*").next_to(soustitre3a,DOWN).scale_in_place(0.75)
        soustitre3v2 = MathTex("\\text{\\emph{Hypothesis : }} \\sqrt{2} = \\frac{a}{b}, \\text{ with } a \\in \\mathbb{Z} \\text{ , } b \\in \\mathbb{Z}^*").scale_in_place(0.75).next_to(titre,direction=DOWN,aligned_edge=LEFT).to_edge(LEFT)
        soustitre4a = MathTex("\\text{Let's suppose that the fraction is fully simplified}").scale_in_place(0.75)
        soustitre4b = MathTex("\\text{that is, }", "gcd(a,b) = 1").next_to(soustitre4a,DOWN).scale_in_place(0.75)
        soustitre4v2 = MathTex("\\text{ and } gcd(a,b) = 1").scale_in_place(0.75).next_to(soustitre3v2)
        bst4 = BraceLabel(soustitre4b[1],"\\text{Their greatest common divisor is } 1 }").scale_in_place(0.75)
        
        eq0 = MathTex("\\text{We have : }","\\sqrt{(2)}","=","\\left ( \\frac{a}{b} \\right )")
        eq1 = MathTex("\\sqrt{(2)}","=","\\left ( \\frac{a}{b} \\right )")
        b1 = BraceLabel(eq1,"\\text{We square each side }",brace_direction=UP)
        eq2 = MathTex("2","=","\\left ( \\frac{a}{b} \\right )^2")
        b2 = BraceLabel(eq2[2],"\\left ( \\frac{a}{b} \\right )^2 = \\frac{a^2}{b^2}")
        eq3 = MathTex("2","=","\\frac{a^2}{b^2}")
        b3 = BraceLabel(eq3,"\\text{Since } b^2 \\neq 0 \\text{, we can multiply each side by } b^2")
        eq4 = MathTex("2b^2","=","a^2")
        b4a = BraceLabel(eq4[0],"\\text{This is even}",brace_direction=UP)
        b4b = BraceLabel(eq4,"\\implies (a \\text{ is even) because we proved that } (n^2 \\text{ even}) \\implies (n \\text{ even})")
        b4c = BraceLabel(eq4[2],"\\text{We can substitute } a \\text{ by } 2k\\text{, with }k \\in \\mathbb{Z}")
        b4 = BraceLabel(eq4[0],"\\text{This is even}",brace_direction=UP)
        eq5 = MathTex("2b^2","=","(2k)^2")
        eq6 = MathTex("2b^2","=","4k^2")
        b6 = BraceLabel(eq6,"\\text{We can divide each side by }2")
        eq7 = MathTex("b^2", "=", "2k^2")
        b7a = BraceLabel(eq4[1:],"\\text{This is even}",brace_direction=UP)
        b7b = BraceLabel(eq4[0],"\\text{So }b \\text{ is even too}")
        eq8a = MathTex("\\text{We have } a \\text{ and } b \\text{ both divisible by }2")
        eq8b = MathTex("\\text{So } gcd(a,b) \geq 2").next_to(eq8a,DOWN)
        eq8c = MathTex("\\text{So } gcd(a,b) \geq 2")
        eq8d = MathTex("\\text{But our hypothesis says that } gcd(a,b) = 1").next_to(eq8c,DOWN)
        eq9a = MathTex("\\text{It would mean that } 1\geq 2")
        eq9b = MathTex("\\text{But we all know this is wrong.}").next_to(eq9a,DOWN)
        eq10a = MathTex("\\text{Our hypothesis is then false.}")
        eq10b = MathTex("\\text{Thus } \\sqrt{2} \\text{ is irrational.}").next_to(eq10a,DOWN)
        eq10c = MathTex("\\sqrt{2} \\text{ is irrational.}").scale_in_place(1.25)
        
        #AnimPart1
        soustitrel2.next_to(titre,direction=DOWN,aligned_edge=LEFT).to_edge(LEFT)
        self.play(ShowCreation(titre1))
        self.wait()
        self.play(Transform(titre1,titre))
        self.wait()
        self.play(ShowCreation(soustitrel1))
        self.wait()
        self.play(Transform(soustitrel1,soustitrel2))
        self.wait(2)
        
        
        self.add(eql0a)
        self.wait()
        self.play(FadeOut(eql0a))
        self.play(FadeIn(eql0b))
        self.wait(2)
        self.play(Transform(eql0b,eql1))
        self.wait()
        self.play(FadeIn(bl1))
        self.wait()
        self.play(FadeOut(bl1))
        self.wait()
        self.play(Transform(eql0b,eql2))
        self.wait()
        self.play(FadeIn(bl2))
        self.wait()
        self.play(FadeOut(bl2))
        self.wait()
        self.play(Transform(eql0b,eql3))
        self.wait()
        self.play(FadeIn(bl3))
        self.wait()
        self.play(FadeOut(bl3))
        self.wait()
        self.play(Transform(eql0b,eql4))
        self.wait()
        self.play(FadeIn(bl4))
        self.wait()
        self.play(FadeOut(bl4))
        self.wait()
        self.play(Transform(eql0b,eql5))
        self.wait()
        self.play(FadeIn(bl5a))
        self.wait()
        self.play(FadeIn(bl5b))
        self.wait()
        self.play(FadeOut(eql0b),FadeOut(bl5a),FadeOut(bl5b))
        self.wait()
        self.play(FadeIn(eql6))
        self.wait()
        self.play(FadeIn(bl6))
        self.wait(2)
        self.play(FadeOut(eql6),FadeOut(soustitrel1),FadeOut(bl6))
        self.wait(2)
        
        
        
        #AnimPart2
        self.play(ShowCreation(soustitre1))
        self.wait()
        self.play(Uncreate(soustitre1))
        self.play(ShowCreation(soustitre2a),ShowCreation(soustitre2b))
        self.wait(3)
        self.play(Uncreate(soustitre2a),Uncreate(soustitre2b))
        self.play(ShowCreation(soustitre3a),ShowCreation(soustitre3b))
        self.wait(3)
        self.play(Transform(soustitre3b,soustitre3v2),Uncreate(soustitre3a))
        self.play(ShowCreation(soustitre4a),ShowCreation(soustitre4b))
        self.wait(2)
        self.play(FadeIn(bst4))
        self.wait()
        self.play(FadeOut(bst4))
        self.wait()
        self.play(Transform(soustitre4b,soustitre4v2),ReplacementTransform(soustitre4a,eq0))
        self.wait()
        self.play(ReplacementTransform(eq0,eq1))
        self.wait()
        self.play(FadeIn(b1))
        self.wait()
        self.play(FadeOut(b1))
        self.wait()
        self.play(Transform(eq1,eq2))
        self.wait()
        self.play(FadeIn(b2))
        self.wait()
        self.play(FadeOut(b2))
        self.wait()
        self.play(Transform(eq1,eq3))
        self.wait()
        self.play(FadeIn(b3))
        self.wait()
        self.play(FadeOut(b3))
        self.wait()
        self.play(Transform(eq1,eq4))
        self.wait()
        self.play(FadeIn(b4a))
        self.wait()
        self.play(FadeIn(b4b))
        self.wait()
        self.play(FadeOut(b4a),FadeOut(b4b))
        self.wait()
        self.play(FadeIn(b4c))
        self.wait(2)
        self.play(FadeOut(b4c))
        self.wait()
        self.play(Transform(eq1,eq5))
        self.wait()
        self.play(Transform(eq1,eq6))
        self.wait()
        self.play(FadeIn(b6))
        self.wait()
        self.play(FadeOut(b6))
        self.wait()
        self.play(Transform(eq1,eq7))
        self.wait()
        self.play(FadeIn(b7a))
        self.wait()
        self.play(FadeIn(b7b))
        self.wait()
        self.play(FadeOut(b7a),FadeOut(b7b))
        self.wait()
        self.play(Transform(eq1,eq8a))
        self.play(ShowCreation(eq8b))
        self.wait()
        self.play(Uncreate(eq1))
        self.play(Transform(eq8b,eq8c))
        self.play(ShowCreation(eq8d))
        self.wait(2)
        self.play(Uncreate(eq8b),Transform(eq8d,eq9a))
        self.play(ShowCreation(eq9b))
        self.wait(3)
        self.play(Uncreate(eq8d),Transform(eq9b,eq10a),FadeOut(soustitre3b),FadeOut(soustitre4b))
        self.play(ShowCreation(eq10b))
        self.wait(2)
        self.play(Transform(eq10b,eq10c),Uncreate(eq9b),Uncreate(titre1))
        self.wait(4)
        self.play(FadeOut(eq10b))
        self.wait()
        
        
        
        
        
      
